#!/usr/bin/env bash

if [[ -e "$HOME"/.config/system/firstboot-done ]]; then
		echo "First boot setup already complete"
		exit 0
fi

(
echo "# Waiting for internet"
until /usr/bin/ping -qc 1 flathub.org; do sleep 1; done

echo "00"
echo "# Removing filtered Flathub repo"
/usr/bin/flatpak remote-delete flathub --force || :
if [[ "$?" != 0 ]]; then 
		zenity --error --text="Removing filtered Flathub repo failed"
		exit 1
fi

echo "3"
echo "# Enabling Flathub"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [[ "$?" != 0 ]]; then 
		zenity --error --text="Adding Flathub failed"
		exit 1
fi

echo "5"
echo "# Replacing Fedora user Flatpaks with Flathub"
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1)
if [[ "$?" != 0 ]]; then 
		zenity --error --text="Replacing Fedora Flatpaks failed"
		exit 1
fi

echo "20"
echo "# Removing preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all || :
if [[ "$?" != 0 ]]; then 
		zenity --error --text="Removing preinstalled Flatpaks failed"
		exit 1
fi

echo "25"
echo "# Removing Fedora Flatpak repo"
/usr/bin/flatpak remote-delete fedora --force || :
if [[ "$?" != 0 ]]; then 
		zenity --error --text="Removing preinstalled Flatpaks failed"
		exit 1
fi

echo "30"
flatpaks=(
	"org.pulseaudio.pavucontrol"
	"io.mpv.Mpv"
	"com.github.wwmm.easyeffects"
	"com.github.tchx84.Flatseal"
)

i=0
for pkg in $flatpaks; do
	echo "# Installing ${pkg}"
	/usr/bin/flatpak install --user --noninteractive flathub $pkg
	if [[ "$?" != 0 ]]; then
		zenity --error \
			--text="Installing ${pkg} failed"
		exit 1
	fi
	i=$((i+1))
	echo "${i}/${flatpaks_count} * (90-35) + 30" | bc -l | cut -d "." -f1
done

echo "# Enabling Flatpak auto update"
/usr/bin/systemctl --user enable --now flatpak-user-update.timer
if [[ "$?" != 0 ]]; then 
	zenity --error \
		--text="Enabling Flatpak auto update failed"
	exit 1
fi

echo "95"
echo "# Writing configurations"
mkdir -p "$HOME"/.config/system
touch "$HOME"/.config/system/firstboot-done

) |
	zenity --progress --title="First Boot Setup" --percentage=0 --auto-close --no-cancel --width=300

if [[ "$?" != 0 ]]; then
	zenity --error \
		--text="First boot setup failed"
fi
